// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwFdtGbvoPsZrTflCNn3WVtES9ixzb7Q',
    appId: '1:1007999721953:web:c203734fc87e3aae29b2a0',
    messagingSenderId: '1007999721953',
    projectId: 'fir-todo-af08b',
    authDomain: 'fir-todo-af08b.firebaseapp.com',
    storageBucket: 'fir-todo-af08b.firebasestorage.app',
    measurementId: 'G-DF3NMBEEPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEV9DU-RjvJEpiOTEGjBg3c_i4Pe68PE4',
    appId: '1:1007999721953:android:231f1c80b3b996ac29b2a0',
    messagingSenderId: '1007999721953',
    projectId: 'fir-todo-af08b',
    storageBucket: 'fir-todo-af08b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7HOzqE7bzjHXtqeGk34Gs7x9FAA_GMpQ',
    appId: '1:1007999721953:ios:c5738f82d7f3663f29b2a0',
    messagingSenderId: '1007999721953',
    projectId: 'fir-todo-af08b',
    storageBucket: 'fir-todo-af08b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodo',
  );

}